from __future__ import annotations

from typing import List, Optional, Sequence, Tuple


from quick_mag.structure import ChemicalStructure, PerovskiteGenerationParameters

# formula_mode -> (builder function name, element kwargs to emit for that mode).
_MODE_BUILDERS = {
    "perovskite": ("generate_single_perovskite", ("a_site", "b_site", "x_site")),
    "double": ("generate_double_perovskite", ("a_site", "b_site", "b2_site", "x_site")),
    "quadruple": (
        "generate_quadruple_perovskite",
        ("a_site", "a2_site", "b_site", "x_site"),
    ),
    "dq": ("generate_dq_perovskite", ("a_site", "a2_site", "b_site", "b2_site", "x_site")),
    "high_entropy": (
        "generate_high_entropy_perovskite",
        ("a_sites", "b_sites", "x_sites"),
    ),
}

# PerovskiteGenerationParameters field backing each emitted element kwarg.
_ELEMENT_FIELDS = {
    "a_site": "a_site_element",
    "b_site": "b_site_element",
    "x_site": "x_site_element",
    "a2_site": "a2_site_element",
    "b2_site": "b2_site_element",
    "a_sites": "high_entropy_a_sites",
    "b_sites": "high_entropy_b_sites",
    "x_sites": "high_entropy_x_sites",
}


def _num(value: object) -> str:
    """Round-trippable literal for a scalar number."""
    return repr(float(value))


def _distribution_literal(entries: Sequence[Tuple[str, float]]) -> str:
    items = ", ".join(f"({str(sym)!r}, {float(frac)!r})" for sym, frac in entries)
    return f"[{items}]"


def _builder_call(structure: ChemicalStructure) -> Tuple[str, str]:
    """Return ``(function_name, call_source)`` for one structure."""
    params: PerovskiteGenerationParameters = structure.generation_parameters
    mode = getattr(params, "formula_mode", "perovskite")
    func_name, element_kwargs = _MODE_BUILDERS.get(mode, _MODE_BUILDERS["perovskite"])

    a = 2.0 * float(params.center_to_vertex_distance_x)
    b = 2.0 * float(params.center_to_vertex_distance_y)
    c = 2.0 * float(params.center_to_vertex_distance_z)
    n_cells = (
        int(params.n_oct_x) + 1,
        int(params.n_oct_y) + 1,
        int(params.n_oct_z) + 1,
    )
    tilt_angles = (
        float(params.tilt_angle_x_deg),
        float(params.tilt_angle_y_deg),
        float(params.tilt_angle_z_deg),
    )

    lines = [f"            {structure.name!r},"]
    for kwarg in element_kwargs:
        field = _ELEMENT_FIELDS[kwarg]
        value = getattr(params, field)
        if kwarg.endswith("_sites"):
            lines.append(f"            {kwarg}={_distribution_literal(value)},")
        else:
            lines.append(f"            {kwarg}={str(value)!r},")

    lines.append(f"            a={_num(a)}, b={_num(b)}, c={_num(c)},")
    lines.append(
        f"            n_cells_x={n_cells[0]}, n_cells_y={n_cells[1]}, "
        f"n_cells_z={n_cells[2]},"
    )
    lines.append(f"            tilt_system={str(params.tilt_system)!r},")
    lines.append(
        f"            tilt_angles_deg=({_num(tilt_angles[0])}, "
        f"{_num(tilt_angles[1])}, {_num(tilt_angles[2])}),"
    )
    lines.append(f"            periodic={bool(params.periodic)},")

    call = f"{func_name}(\n" + "\n".join(lines) + "\n        )"
    return func_name, call


def generate_build_script(
    entries: Sequence[Tuple[Optional[str], ChemicalStructure]],
) -> str:
    """Return Python source that regenerates ``entries`` and writes CIFs.

    Each entry is ``(group_name_or_None, structure)``. Structures with
    ``generation_parameters is None`` are skipped (noted in the header).
    """
    kept: List[Tuple[Optional[str], ChemicalStructure]] = []
    skipped: List[str] = []
    for group_name, structure in entries:
        if getattr(structure, "generation_parameters", None) is None:
            skipped.append(structure.name)
        else:
            kept.append((group_name, structure))

    header_lines = [
        "#!/usr/bin/env python",
        '"""Auto-generated by the Molecular Visualization builder.',
        "",
        "Regenerates the saved structures below and writes each one to disk as a CIF.",
        "Requires the molecular_visualization package on the import path",
        "(install it once with `pip install -e .` from the repo root).",
    ]
    if skipped:
        header_lines.append("")
        header_lines.append(
            "Skipped (no generation parameters, e.g. loaded from a file):"
        )
        for name in skipped:
            header_lines.append(f"  - {name}")
    header_lines.append('"""')

    used_functions = sorted({_builder_call(structure)[0] for _, structure in kept})
    entry_lines = []
    for group_name, structure in kept:
        _, call = _builder_call(structure)
        group_literal = repr(group_name) if group_name is not None else "None"
        entry_lines.append(f"        ({group_literal}, {call}),")
    entries_block = "\n".join(entry_lines)

    if used_functions:
        import_block = "from generation import (\n" + "".join(
            f"    {name},\n" for name in used_functions
        ) + ")"
    else:
        import_block = "from generation import generate_single_perovskite  # noqa: F401"

    body = f'''
import argparse
from pathlib import Path

{import_block}
from quick_mag.export_utils import export_structure


def build_structures():
    """Each item is ``(group_name_or_None, ChemicalStructure)``."""
    return [
{entries_block}
    ]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate saved structures and write each one as a CIF."
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        default="generated_structures",
        help="Directory to write structures into (default: %(default)s).",
    )
    args = parser.parse_args()
    out_dir = Path(args.output_dir).expanduser()

    structures = build_structures()
    for group, structure in structures:
        destination = out_dir / group if group else out_dir
        destination.mkdir(parents=True, exist_ok=True)
        export_structure(structure, destination)
        print(f"Wrote {{structure.name}} -> {{destination}}")

    print(f"Done. {{len(structures)}} structure(s) written under {{out_dir}}.")


if __name__ == "__main__":
    main()
'''

    return "\n".join(header_lines) + "\n" + body
